"""monotonic template revisions"""

import sqlalchemy as sa
from alembic import op

revision = "889fb7fce0d2"
down_revision = "fc5722fefb26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attendance_records", sa.Column("template_revision", sa.Integer(), nullable=True))
    op.add_column(
        "face_templates", sa.Column("revision", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "users", sa.Column("photo_revision", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("active_photo_revision", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active_photo_revision")
    op.drop_column("users", "photo_revision")
    op.drop_column("face_templates", "revision")
    op.drop_column("attendance_records", "template_revision")
    # ### end Alembic commands ###
